### ISSUE TITLE
Nicer dashboard for last round's scores 

### ISSUE THREAD

**Issue by AnotherKamila** [netsec-ethz/scionlab-workshop#11]
Is it possible to change the influxdb's query to only select the last round's data for that table? something like `... WHERE round == max(round)`

**Comment by mkowalski** [comment]
Done. http://monit.netsec.inf.ethz.ch/d/Iy-KxH2Zz/viscon-scionlab-workshop-demo?orgId=1&from=1570014354009&to=1570034656482
