### ISSUE TITLE
The submissions seem to take some >1 round to be in effect

### ISSUE THREAD

**Issue by juagargi** [netsec-ethz/scionlab-workshop#6]
It seems that when we call `scionlab.sh submit myscript.py`, said script is not really run in the next round, but later.

- [ ] Test / reproduce
- [ ] Fix if needed

**Comment by AnotherKamila** [comment]
First poke at testing it:

- [ ] run locally
- [ ] submit a file that prints its version, wait for round, submit v2, wait for round
- [ ] check logs for version printout
- [ ] if it appears: check round data in webserver to determine whether the problem is there or in buildbot

**Comment by AnotherKamila** [comment]
Cannot reproduce :-(

(I reproduced a possibly related problem by having leftover data from a previous run lying around -- but it really doesn't look like that's what happened during the contest :-/)

**Comment by AnotherKamila** [comment]
Reproduced by accident in prod, and it is coming from the webserver. I have the round files that show this behaviour. @giacgiuliari is investigating.
